PronadjiUBanovcima/Controllers/HomeController.cs
using PronadjiUBanovcima.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PronadjiUBanovcima.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PronadjiUBanovcima/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PronadjiUBanovcima.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Security.Claims;


namespace PronadjiUBanovcima.Controllers
{
    //[Authorize(Roles="Admin")]
    public class InfoController : Controller
    {


         public InfoController()
            : this(new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext())))
        {
        }

         public InfoController(UserManager<ApplicationUser> userManager)
        {
            UserManager = userManager;
        }


        private ApplicationDbContext db = new ApplicationDbContext();
        public UserManager<ApplicationUser> UserManager { get; private set; }
        // GET: /Info/
       
        public ActionResult Index(string SearchString)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userIdentity = (ClaimsIdentity)User.Identity;
                var claims = userIdentity.Claims;
                var roleClaimType = userIdentity.RoleClaimType;
                var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

                ViewBag.User = roles[0].Value;
            }
            else
                ViewBag.User = "Anoniman";
            List<Info> podaci = new List<Info>();

            if (SearchString != "")
            {
                podaci = db.Podaci.Where(p => p.Firma.Contains(SearchString)).ToList();
                List<Info> podaciRaw = db.Podaci.ToList();
                List<Delatnost> delatnosti = db.Delatnosti.Where(d => d.Naziv.Contains(SearchString)).ToList();

                int[] delIds = new int[delatnosti.Count];
                for (int i = 0; i < delatnosti.Count; i++)
                {
                    delIds[i] = delatnosti[i].Id;
                }

                podaci.AddRange(db.Podaci
                   .Where(x => x.ListaDelatnosti.Any(r => delIds.Contains(r.Id))).ToList());

                List<Tag> tagovi = db.Tagovi.Where(t => t.Naziv.Contains(SearchString)).ToList();
                int[] tagIds = new int[tagovi.Count];
                for (int i = 0; i < tagovi.Count; i++)
                    tagIds[i] = tagovi[i].Id;

                podaci.AddRange(db.Podaci.Where(x => x.ListaTagova.Any(t => tagIds.Contains(t.Id))).ToList());
                podaci = podaci.Distinct().ToList();
            }
            else
                podaci = db.Podaci.ToList();

            if (podaci.Count > 0)
                return View(podaci);
            else
                return RedirectToAction("Index", "Home", new { message = "Nema rezultata."});
        }
        [HttpPost]
        [AllowAnonymous]
       
        // GET: /Info/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Info info = db.Podaci.Find(id);
            if (info == null)
            {
                return HttpNotFound();
            }
            return View(info);
        }

        // GET: /Info/Create
        public ActionResult Create()
        {
            return View();
        }

        //// POST: /Info/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Firma,Opis,Telefon,Adresa,Sajt,Email")] Info info)
        {
            if (ModelState.IsValid)
            {
                db.Podaci.Add(info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(info);
        }

        // GET: /Info/Edit/5
        
        public  ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Info info = db.Podaci.Find(id);
            if (info == null)
            {
                return HttpNotFound();
            }
            var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var role =  RoleManager.FindByName("Osnovni");
         
            bool osnovni = info.Klijent.Roles.ToList<IdentityUserRole>()[0].Role == role;
            ViewBag.Korisnik = osnovni;
            return View(info);
        }

        // POST: /Info/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Firma,Opis,Telefon,Adresa,Sajt,Email")] Info info)
        {
            var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var role = RoleManager.FindByName("Osnovni");
            bool osnovni = Request.Form["[0].Role.Name"] == role.Name;
            ViewBag.Korisnik = osnovni;
            string klijent = Request.Form["Klijent.Id"];

            if (ModelState.IsValid)
            {
                string korisnickiPaket = Request.Form["rbtn"];
               
                string staraRola = Rola(korisnickiPaket);
                UserManager.RemoveFromRole(klijent, staraRola);
                UserManager.AddToRole(klijent, korisnickiPaket);
                db.Entry(info).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(info);
        }

        private string Rola(string korisnickiPaket)
        {
            if (korisnickiPaket == "Osnovni")
                return "Premium";
            return "Osnovni";
        }

        // GET: /Info/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Info info = db.Podaci.Find(id);
            if (info == null)
            {
                return HttpNotFound();
            }
            return View(info);
        }

        // POST: /Info/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Info info = db.Podaci.Find(id);
            db.Podaci.Remove(info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PronadjiUBanovcima/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="container">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</div>

PronadjiUBanovcima/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="container">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>

</div>

PronadjiUBanovcima/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Najnoviji oglasi";
}
@model IEnumerable<PronadjiUBanovcima.Models.Info>


     @*<span>@ViewBag.Message</span>*@
    <div class="row" id="search">
        
        @using (Html.BeginForm("Index", "Info", FormMethod.Post))
    {
            
            <div class="col-lg-11 col-xs-12">
                <div class="input-group input-group-lg">
                    <input name="SearchString" type="text" class="form-control" placeholder="Pretraga..." />
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"> <span class="glyphicon glyphicon-search"></span> </button>
                    </span>
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        }
    </div>


<div class="bottom">
    <div class="row">
        <a href="#">
            <div class="bottom-buttons col-md-6 col-sm-6 col-xs-12">
                <div class="inner">
                    besplatni portal
                </div>
            </div>
        </a>
        <a href="#">
            <div class="bottom-buttons col-md-6 col-sm-6 col-xs-12">
                <div class="inner">
                    premium portal
                </div>
            </div>
        </a>
    </div>
</div>